#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_http_server.h"
#include "cJSON.h"
#include "web_server.h"
#include "nvs_config.h"
#include "wifi_manager.h"
#include "dns_responder.h"

static const char *TAG = "web_srv";

static httpd_handle_t s_server = NULL;

/* External embedded HTML file (generated by EMBED_FILES) */
extern const uint8_t web_config_html_start[] asm("_binary_web_config_html_start");
extern const uint8_t web_config_html_end[] asm("_binary_web_config_html_end");

/* ================================================================
 * URI Handlers
 * ================================================================ */

/* GET / — serve the config HTML page */
static esp_err_t handle_get_root(httpd_req_t *req)
{
    size_t html_len = web_config_html_end - web_config_html_start;
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_send(req, (const char *)web_config_html_start, html_len);
    return ESP_OK;
}

/* GET /api/config — return current config as JSON */
static esp_err_t handle_get_config(httpd_req_t *req)
{
    const config_t *cfg = nvs_config_get();
    cJSON *root = cJSON_CreateObject();

    cJSON_AddStringToObject(root, "dev_name",   cfg->dev_name);
    cJSON_AddStringToObject(root, "wifi_ssid",  cfg->wifi_ssid);
    cJSON_AddStringToObject(root, "wifi_pass",  "****");  /* mask password */
    cJSON_AddNumberToObject(root, "ap_fallback", cfg->ap_fallback);
    cJSON_AddStringToObject(root, "mqtt_uri",   cfg->mqtt_uri);
    cJSON_AddNumberToObject(root, "mqtt_port",  cfg->mqtt_port);
    cJSON_AddStringToObject(root, "mqtt_user",  cfg->mqtt_user);
    cJSON_AddStringToObject(root, "mqtt_pass",  "****");
    cJSON_AddStringToObject(root, "mqtt_data_t", cfg->mqtt_data_t);
    cJSON_AddStringToObject(root, "mqtt_write_t", cfg->mqtt_write_t);
    cJSON_AddStringToObject(root, "mqtt_stat_t", cfg->mqtt_stat_t);
    cJSON_AddNumberToObject(root, "baudrate",   cfg->baudrate);
    cJSON_AddNumberToObject(root, "data_bits",  cfg->data_bits);
    cJSON_AddNumberToObject(root, "stop_bits",  cfg->stop_bits);
    cJSON_AddNumberToObject(root, "parity",     cfg->parity);
    cJSON_AddStringToObject(root, "reg_list",   cfg->reg_list);
    cJSON_AddNumberToObject(root, "tx_pin",     cfg->tx_pin);
    cJSON_AddNumberToObject(root, "rx_pin",     cfg->rx_pin);
    cJSON_AddNumberToObject(root, "de_pin",     cfg->de_pin);
    cJSON_AddNumberToObject(root, "poll_intv",  cfg->poll_intv);
    cJSON_AddStringToObject(root, "custom1",    cfg->custom1);
    cJSON_AddStringToObject(root, "custom2",    cfg->custom2);
    cJSON_AddStringToObject(root, "custom3",    cfg->custom3);

    char *json_str = cJSON_PrintUnformatted(root);
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json_str, strlen(json_str));
    free(json_str);
    cJSON_Delete(root);
    return ESP_OK;
}

/* POST /save — parse form data and write to NVS */
static esp_err_t handle_post_save(httpd_req_t *req)
{
    char buf[2048] = {0};
    int ret = httpd_req_recv(req, buf, sizeof(buf) - 1);
    if (ret <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Empty body");
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "POST /save body: %s", buf);

    /* Parse URL-encoded form data: key1=val1&key2=val2... */
    char *pair = strtok(buf, "&");
    while (pair) {
        char *eq = strchr(pair, '=');
        if (eq) {
            *eq = '\0';
            char *key = pair;
            char *val = eq + 1;

            /* URL decode (basic: replace + with space) */
            for (char *p = val; *p; p++) {
                if (*p == '+') *p = ' ';
            }

            /* Try to set as number first, then string */
            char *endptr;
            long num = strtol(val, &endptr, 10);
            if (*endptr == '\0' && val[0] != '\0') {
                /* Numeric value */
                nvs_config_set_u32(key, (uint32_t)num);
                nvs_config_set_u16(key, (uint16_t)num);
                nvs_config_set_u8(key, (uint8_t)num);
            } else {
                nvs_config_set_string(key, val);
            }
        }
        pair = strtok(NULL, "&");
    }

    /* Persist to NVS */
    nvs_config_save();

    /* Signal WiFi manager to switch modes */
    wifi_manager_on_config_saved();

    /* Respond success */
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"status\":\"ok\"}");
    return ESP_OK;
}

/* Catch-all handler — redirect to / for captive portal */
static esp_err_t handle_captive_redirect(httpd_req_t *req)
{
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", "http://192.168.4.1/");
    httpd_resp_send(req, NULL, 0);
    return ESP_OK;
}

/* ================================================================
 * Public
 * ================================================================ */

void web_server_start(void)
{
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.max_uri_handlers = 16;
    config.lru_purge_enable = true;
    config.stack_size = 8192;

    if (httpd_start(&s_server, &config) == ESP_OK) {
        ESP_LOGI(TAG, "HTTP server started on port 80");

        /* Register URI handlers */
        httpd_uri_t uri_root = {
            .uri = "/",
            .method = HTTP_GET,
            .handler = handle_get_root,
            .user_ctx = NULL,
        };
        httpd_register_uri_handler(s_server, &uri_root);

        httpd_uri_t uri_config = {
            .uri = "/api/config",
            .method = HTTP_GET,
            .handler = handle_get_config,
            .user_ctx = NULL,
        };
        httpd_register_uri_handler(s_server, &uri_config);

        httpd_uri_t uri_save = {
            .uri = "/save",
            .method = HTTP_POST,
            .handler = handle_post_save,
            .user_ctx = NULL,
        };
        httpd_register_uri_handler(s_server, &uri_save);

        /* Captive portal catch-all — must be registered LAST */
        httpd_uri_t uri_captive = {
            .uri = "/*",
            .method = HTTP_GET,
            .handler = handle_captive_redirect,
        };
        httpd_register_uri_handler(s_server, &uri_captive);

        /* Start DNS responder */
        dns_server_start();
    } else {
        ESP_LOGE(TAG, "Failed to start HTTP server");
    }
}

void web_server_stop(void)
{
    dns_server_stop();
    if (s_server) {
        httpd_stop(s_server);
        s_server = NULL;
        ESP_LOGI(TAG, "HTTP server stopped");
    }
}
